services:
    db:
        image: postgres
        container_name: db
        restart: always
        environment:
            - POSTGRES_USER=tbadge_user
            - POSTGRES_PORT=5432
            - POSTGRES_DB=tbadge
            - POSTGRES_PASSWORD=AN0NXj8mslovefdWB67lkdNGGYVprVFF8
        volumes:
            - db:/var/lib/postgresql/data
        healthcheck:
            test: [ "CMD-SHELL", "pg_isready -U postgres -d postgres" ]
            interval: 10s
            timeout: 5s
            retries: 5
            start_period: 10s
        
    app:
        build: .
        container_name: app
        restart: always
        expose:
            - "8080"
        depends_on:
            db:
              condition: service_healthy
              
    nginx:
        image: nginx
        container_name: nginx
        restart: always
        depends_on:
            - app
        ports:
            - 80:80
        volumes:
            - ./T-Badge.Nginx/nginx.conf:/etc/nginx/nginx.conf
            - ./T-Badge.Nginx/app:/etc/nginx/app

volumes:
    db: